apiVersion: v1
kind: ConfigMap
metadata:
  name: comms-staging-env-config
data:
  ENV: "staging"
  PUBSUB_SUBSCRIPTIONS: "comms-staging-fitness-sub,comms-staging-identity-sub,comms-staging-asset-sub,comms-staging-forecasting-sub"
