apiVersion: v1
kind: ServiceAccount
metadata:
  name: comms-staging-ksa
  namespace: comms-staging
  annotations:
    iam.gke.io/gcp-service-account: comms-staging-sa@ethans-services.iam.gserviceaccount.com
